# Generated by Django 4.0.4 on 2022-05-07 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods_archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('sub_category', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(choices=[('Fridge', 'Fridge'), ('Freezer', 'Freezer'), ('Cabinet', 'Cabinet')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('sub_category', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(choices=[('Fridge', 'Fridge'), ('Freezer', 'Freezer'), ('Cabinet', 'Cabinet')], max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('expiration', models.DateField()),
                ('Days_Left', models.IntegerField()),
                ('updated', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
