# Generated by Django 4.0.1 on 2022-05-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_updates',
            field=models.BooleanField(default=False),
        ),
    ]
